#!/usr/bin/env python
# coding: utf-8

# Load the training data from the MongoDb


import spacy
import pymongo

# Load spaCy models
nlp_dpt = spacy.load('archive/Model_tilldpt/')
nlp_main = spacy.load('archive/Model_tillmainkeywords/')
nlp = spacy.load('archive/Model_industry/')
nlp_company = spacy.load("en_core_web_md")

# Connect to the MongoDB server
client = pymongo.MongoClient("mongodb://Aditya:123456@20.25.72.14:27017/?authMechanism=DEFAULT&authSource=admin")

# Choose the 'news' database
db = client['news']

# Choose the 'news_set' collection
collection = db['news_set']

# Query all data and exclude the _id field
query_result = collection.find({}, {"_id": 0})

# Initialize an empty list to store the data
data_list = []

# Loop through the query result and append each document to the list
for item in query_result:
    data_list.append(item)

# Print the number of documents retrieved
print(f"Retrieved {len(data_list)} documents from 'news_set' collection")

# Close the MongoDB connection
client.close()



# In[5]:


Indus = {
"Accounting": [
    "cashflow",
    "brokerage",
    "securities",
    "debt",
    "liabilities",
    "trading",
    "bookkeeping",
    "accounting",
    "audit",
    "insurance",
    "investor",
    "compliance",
    "mutual funds",
    "retirement",
    "tax",
    "hedge funds",
    "financing",
    "bonds",
    "stocks",
    "costing",
    "assets",
    "cpa",
    "profitability",
    "investing",
    "reporting",
    "ledger",
    "credit",
    "etfs",
    "derivatives",
    "financials",
    "fundraising"
  ],
  "Agriculture & Mining": [
    "iron",
    "corrals",
    "mining",
    "soil",
    "breeding",
    "yogurt",
    "insecticides",
    "herd",
    "quarry",
    "metallurgy",
    "ranching",
    "cattle",
    "cowboy",
    "cows",
    "grazing",
    "rancher",
    "pasture",
    "whey",
    "cream",
    "distribution",
    "machinery",
    "silage",
    "feedlot",
    "steel",
    "copper",
    "cheese",
    "butter",
    "livestock",
    "storage",
    "animal",
    "markets",
    "equipment",
    "commodities",
    "subsidy",
    "milk",
    "exploration",
    "lactose",
    "irrigation",
    "ghee",
    "alloy",
    "aluminum",
    "bauxite",
    "drill",
    "drilling",
    "curd",
    "refinery",
    "hay",
    "smelting",
    "ore",
    "excavation",
    "ice-cream",
    "agriculture",
    "welfare",
    "mine",
    "harvesting",
    "rural",
    "subsidies",
    "dairy",
    "fertilizers",
    "sulfide",
    "crops",
    "geology",
    "pesticides",
    "acreage",
    "fencing",
    "refining"
  ],
  "Airlines/aviation": [
    "cargo",
    "airline",
    "aviation",
    "navigation",
    "fuel",
    "freight",
    "airport",
    "flight",
    "runway",
    "takeoff",
    "aircraft",
    "pilot",
    "landing",
    "turbine",
    "atc",
    "baggage"
  ],
  "Apparel & Fashion": [
    "precious",
    "diamonds",
    "handbags",
    "watches",
    "fashion",
    "trends",
    "cosmetics",
    "jewelry",
    "garments",
    "shopping",
    "merchandising",
    "gems",
    "designer",
    "apparel",
    "clothing",
    "brands",
    "branding",
    "footwear",
    "e-commerce",
    "luxury",
    "textiles",
    "design",
    "fabric",
    "perfumes",
    "accessories"
  ],
  "Architecture & Planning": [
    "building",
    "facilities",
    "bim",
    "sustainability",
    "infrastructure",
    "landscape",
    "architect",
    "planning",
    "blueprint",
    "cad",
    "mechanical",
    "structural",
    "construction",
    "urban",
    "model"
  ],
  "Arts And Crafts": [
    "mosaics",
    "exhibitions",
    "printmaking",
    "opera",
    "artists",
    "theatre",
    "artwork",
    "pottery",
    "playwrights",
    "basketry",
    "painting",
    "leatherwork",
    "aesthetics",
    "dance",
    "ballet",
    "galleries",
    "singers",
    "weaving",
    "jewellery",
    "embroidery",
    "orchestras",
    "drawing",
    "designers",
    "composers",
    "critique",
    "actors",
    "knitting",
    "sculpture",
    "criticism",
    "critiques",
    "musicals",
    "woodwork",
    "festivals",
    "textiles",
    "audiences",
    "performers",
    "performance",
    "musicians",
    "repertoire",
    "glasswork",
    "directors"
  ],
  "Automotive": [
    "buses",
    "crash",
    "gasoline",
    "accident",
    "motors",
    "parts",
    "cars",
    "trucks",
    "hybrids",
    "diesel",
    "suvs",
    "automakers",
    "electric",
    "motorcycles",
    "racing",
    "dealers",
    "carsales",
    "mechanics",
    "accessories"
  ],
  "Aerospace": [
    "navy",
    "airforce",
    "propulsion",
    "spacecraft",
    "manufacturing",
    "fighter",
    "radar",
    "jet",
    "bomber",
    "defense",
    "satellite",
    "flight",
    "aerospace",
    "missile",
    "avionics",
    "combat",
    "aerodynamics",
    "spacelaunch",
    "aeroplane",
    "aircraft",
    "weapons",
    "helicopter",
    "shuttle",
    "astronomy"
  ],
  "Banking": [
    "mortgage",
    "loan",
    "technology",
    "insurance",
    "credit",
    "banking",
    "interest",
    "investment",
    "finance",
    "funds",
    "banking regulations"
  ],
  "Biotechnology": [
    "biotech",
    "dna",
    "genomics",
    "diagnostics",
    "patents",
    "clinical",
    "proteins",
    "bioinformatics",
    "vaccines",
    "drugs"
  ],
  "Capital Markets": [
    "sec",
    "yields",
    "volatility",
    "ipos",
    "indexing",
    "brokerage",
    "investing",
    "hedge funds",
    "rebalancing",
    "bonds",
    "etfs",
    "derivatives",
    "diversification",
    "stocks",
    "trading",
    "mutual funds"
  ],
  "Chemicals": [
    "fuels",
    "adhesives",
    "gasoline",
    "polymers",
    "manufacturing",
    "chemicals",
    "bleach",
    "petrochemicals",
    "detergents",
    "fertilizers",
    "plastics",
    "synthetic",
    "resins",
    "pesticides",
    "refining",
    "solvents"
  ],
  "Civil Engineering": [
    "highways",
    "bridges",
    "drilling",
    "flooding",
    "tunnels",
    "engineering",
    "infrastructure",
    "railways",
    "contracting",
    "drainage",
    "surveying",
    "planting",
    "construction"
  ],
  "Computers & Electronics": [
    "technology",
    "network",
    "hard drive",
    "development",
    "chip",
    "video",
    "video card",
    "ibm",
    "transformers",
    "graphics",
    "patching",
    "cameras",
    "ipv6",
    "wifi",
    "displays",
    "subnet",
    "connectors",
    "keyboard",
    "database",
    "semiconductors",
    "phishing",
    "graphics card",
    "privacy",
    "voip",
    "electronics",
    "robotics",
    "cables",
    "cyberattack",
    "google",
    "action",
    "demand",
    "wearables",
    "accessibility",
    "console",
    "lan",
    "application",
    "microprocessor",
    "simulation",
    "biometrics",
    "components",
    "encryption",
    "artificial",
    "cpu",
    "wafer",
    "topology",
    "processor",
    "storage",
    "oracle",
    "intelligence",
    "smartphones",
    "amazon",
    "circuit",
    "interface",
    "rpg",
    "circuits",
    "asus",
    "augmented reality",
    "batteries",
    "esports",
    "printer",
    "operating",
    "apple",
    "vulnerability",
    "semiconductor",
    "huawei",
    "nvidia",
    "hp",
    "psu",
    "capacitors",
    "leds",
    "protocol",
    "hacking",
    "applications",
    "scanner",
    "market",
    "online",
    "lenovo",
    "program",
    "vpn",
    "samsung",
    "firewall",
    "packet",
    "yahoo",
    "intel",
    "dell",
    "authentication",
    "software",
    "virtual reality",
    "ram",
    "appliances",
    "cisco",
    "system",
    "wires",
    "automation",
    "ssd",
    "motherboard",
    "switch",
    "router",
    "accessory",
    "platform",
    "televisions",
    "motors",
    "products",
    "malware",
    "ipv4",
    "gadgets",
    "microsoft",
    "multiplayer",
    "amd",
    "cloud",
    "wan",
    "tablets",
    "networking"
  ],
  "Cosmetics": [
    "beauty",
    "distribution",
    "haircare",
    "organic",
    "fragrance",
    "cosmetic",
    "products",
    "brands",
    "fashion",
    "makeup",
    "skincare",
    "advertising",
    "marketing",
    "natural"
  ],
  "Education": [
    "scholarship",
    "student",
    "curriculum",
    "scholarships",
    "coaches",
    "tuition",
    "consulting",
    "learning",
    "schools",
    "seminar",
    "board",
    "development",
    "faculty",
    "students",
    "degrees",
    "enrollment",
    "strategies",
    "certification",
    "institutes",
    "college",
    "textbooks",
    "certificates",
    "tutoring",
    "mentoring",
    "admissions",
    "testing",
    "course",
    "endowment",
    "universities",
    "trainers",
    "skills",
    "degree",
    "classroom",
    "degree programs",
    "university",
    "assessment",
    "tests",
    "lecture",
    "exams",
    "training",
    "teachers",
    "e-learning",
    "education",
    "performance",
    "accreditation",
    "program",
    "grants",
    "grant",
    "academics",
    "programs"
  ],
  "Energy & Utilities": [
    "environmental",
    "water",
    "oil",
    "solar",
    "renewable",
    "distribution",
    "petroleum",
    "gas",
    "hydroelectric",
    "environment",
    "power",
    "pipeline",
    "drilling",
    "energy",
    "crude",
    "wind",
    "refining",
    "geothermal",
    "transmission",
    "conservation",
    "nuclear",
    "electric",
    "coal",
    "efficiency",
    "non-renewable"
  ],
  "Media & Entertainment": [
    "vfx",
    "studio",
    "ratings",
    "network",
    "theatres",
    "music production",
    "photographer",
    "video",
    "sets",
    "aperture",
    "merchandise",
    "lighting",
    "cameras",
    "publishing",
    "platforms",
    "advertising",
    "tv",
    "celebrity",
    "shutter",
    "theater",
    "subscription",
    "sound",
    "gallery",
    "cable",
    "movie",
    "studios",
    "cinema",
    "publishers",
    "distribution",
    "cinematography",
    "broadcasting",
    "a&r",
    "showbiz",
    "production",
    "flash",
    "box-office",
    "lens",
    "streaming",
    "journalism",
    "profitability",
    "musicians",
    "visual",
    "audience",
    "print",
    "posters",
    "lights",
    "animation",
    "exposure",
    "strategies",
    "content",
    "post-production",
    "newsrooms",
    "tours",
    "music videos",
    "culture",
    "film",
    "readership",
    "landscape",
    "media",
    "festivals",
    "camera",
    "online",
    "concerts",
    "circulation",
    "digital",
    "broadcast",
    "songs",
    "awards",
    "theatre",
    "red-carpet",
    "recordings",
    "editing",
    "exhibitors",
    "arts",
    "music",
    "engagement",
    "image",
    "rankings",
    "actors",
    "audio",
    "social-media",
    "licensing",
    "albums",
    "reviews",
    "transmission",
    "radio",
    "portrait",
    "screenplay",
    "television",
    "glamour",
    "networking",
    "directors"
  ],
  "Environmental Services": [
    "emissions",
    "technology",
    "eco-friendly",
    "hydro",
    "solar",
    "renewable",
    "alternative energy",
    "habitat",
    "environmentalism",
    "environment",
    "ecology",
    "pollution",
    "carbon",
    "water management",
    "waste",
    "wind",
    "recycling",
    "ecosystem",
    "geothermal",
    "conservation",
    "greenhouse gases",
    "climate",
    "sustainability",
    "biomass",
    "renewables",
    "natural resources",
    "renewal",
    "renewable energy"
  ],
  "Facilities Services": [
    "maintenance",
    "plumbing",
    "janitorial",
    "security",
    "electrical",
    "repair",
    "groundskeeping",
    "landscaping",
    "cleaning",
    "hvac"
  ],
  "Food & Beverages": [
    "hops",
    "spawning",
    "food-safety",
    "trawlers",
    "cigarettes",
    "wharves",
    "taxation",
    "yeast",
    "corks",
    "smoking",
    "haccp",
    "flavors",
    "catering",
    "grocery",
    "food",
    "blending",
    "aromas",
    "menu",
    "addiction",
    "varieties",
    "cuisine",
    "sommelier",
    "vineyards",
    "vaping",
    "ingredients",
    "genetically-modified",
    "fishing",
    "livestock",
    "tobacco",
    "restaurant",
    "distillation",
    "pond",
    "recipes",
    "mariculture",
    "seafood",
    "grapes",
    "bottling",
    "aquaculture",
    "boats",
    "beverage",
    "cafe",
    "alcohol",
    "wineries",
    "market",
    "fermentation",
    "packing",
    "fast-food",
    "fishery",
    "farming",
    "fisheries",
    "nicotine",
    "dining",
    "organic",
    "nutrition",
    "agriculture",
    "fish",
    "liquor",
    "farmer",
    "hatcheries",
    "spirits",
    "prevention",
    "harvesting",
    "barley",
    "tasting",
    "cooking",
    "nets"
  ],
  "Fund-raising": [
    "incubator",
    "venture",
    "crowdfunding",
    "acquisition",
    "ipo",
    "equity",
    "start-up",
    "accelerator",
    "investor",
    "angel",
    "capital",
    "financing",
    "merger",
    "investment",
    "fundraising"
  ],
  "Gambling & Casinos": [
    "slots",
    "casino-gaming",
    "horse-racing",
    "wagering",
    "betting",
    "luck",
    "bookmaker",
    "bingo",
    "jackpot",
    "lottery",
    "blackjack",
    "prize",
    "sportsbook",
    "gambling",
    "odds",
    "casino",
    "casinos",
    "poker",
    "roulette",
    "keno",
    "winnings",
    "baccarat",
    "sports-betting",
    "craps"
  ],
  "Government": [
    "budgeting",
    "taxes",
    "appointments",
    "election",
    "agencies",
    "investigations",
    "bureaucracy",
    "procurement",
    "development",
    "lobbying",
    "taxation",
    "regulation",
    "political",
    "contracts",
    "security",
    "politics",
    "immigration",
    "representation",
    "healthcare",
    "regulatory",
    "relations",
    "minister",
    "interests",
    "regulations",
    "representing",
    "legislation",
    "economy",
    "employment",
    "audits",
    "education",
    "law",
    "laws",
    "policy",
    "lawmaking",
    "decisions",
    "government",
    "advocacy",
    "budget"
  ],
  "Graphic Design": [
    "studio",
    "vfx",
    "illustration",
    "graphic",
    "user-interface",
    "visuals",
    "characters",
    "animation",
    "animators",
    "logo",
    "post-production",
    "social",
    "graphics",
    "layout",
    "cgi",
    "creativity",
    "branding",
    "advertising",
    "storytelling",
    "motion",
    "cartoons",
    "3d",
    "digital",
    "design",
    "visual",
    "typography"
  ],
  "Import And Export": [
    "intermodal",
    "supply chain",
    "logistics",
    "customs",
    "maritime",
    "sanctions",
    "merchandise",
    "trade",
    "consolidation",
    "congestion",
    "ports",
    "vessels",
    "quotas",
    "cartons",
    "chartering",
    "wrappers",
    "containers",
    "freight",
    "supply-chain",
    "embargoes",
    "packaging",
    "cans",
    "logistics-technology",
    "distribution",
    "transportation",
    "import",
    "dispensers",
    "globalization",
    "seafaring",
    "tariffs",
    "delivery",
    "road",
    "trucks",
    "capacity",
    "blister",
    "safety",
    "storage",
    "fuel",
    "quality-control",
    "cargo",
    "navigation",
    "infrastructure",
    "supply-chain-management",
    "palletizing",
    "logistic-costs",
    "jars",
    "export",
    "salvage",
    "package",
    "carriers",
    "railway",
    "warehousing",
    "planes",
    "tracking",
    "logistic-operations",
    "maritime law",
    "packing",
    "inventory",
    "routes",
    "maritime safety",
    "procurement",
    "airfreight",
    "stretch",
    "highway",
    "shipping",
    "rail",
    "transport",
    "railroad",
    "currency",
    "fleet",
    "pouches",
    "trucking",
    "asset-management",
    "roads",
    "trains",
    "trays",
    "drums",
    "courier",
    "dispatch"
  ],
  "Hospital & Health Care": [
    "biotechnology",
    "herbal",
    "diagnosis",
    "breeding",
    "hospital",
    "pharmaceutical",
    "aromatherapy",
    "magnetotherapy",
    "disability",
    "imaging",
    "homeopathy",
    "biotech",
    "medical",
    "recovery",
    "psychiatry",
    "disease",
    "mentalhealth",
    "injury prevention",
    "naturopathy",
    "addiction",
    "pharmaceuticals",
    "disease prevention",
    "pilates",
    "acupuncture",
    "animalcare",
    "trials",
    "clinics",
    "supplements",
    "cardio",
    "veterinary",
    "strength training",
    "weight",
    "patents",
    "insurance",
    "therapy",
    "drugs",
    "chiropractic",
    "surgery",
    "anxiety",
    "exercise",
    "physician",
    "equipment",
    "diet",
    "caregiver",
    "medication",
    "grooming",
    "pets",
    "therapies",
    "patient",
    "hydrotherapy",
    "clinic",
    "psychotherapy",
    "treatment",
    "hospitals",
    "petcare",
    "healthcare",
    "clinical",
    "stress",
    "workouts",
    "meditation",
    "psychologist",
    "nurse",
    "wellness",
    "diagnostic",
    "health care",
    "suicide",
    "nutrition",
    "mental health",
    "quality",
    "diagnostics",
    "doctor",
    "reflexology",
    "reiki",
    "yoga",
    "medicine",
    "regulatory",
    "facilities",
    "care",
    "health",
    "pharmacy",
    "fitness",
    "depression",
    "vaccines",
    "ayurveda",
    "lifestyle",
    "prescription"
  ],
  "Hospitality": [
    "banquets",
    "hotels",
    "golf",
    "bars",
    "cafes",
    "airports",
    "room service",
    "valet",
    "events",
    "catering",
    "casino",
    "resorts",
    "spa",
    "tourist",
    "cruise ships",
    "airlines",
    "restaurants",
    "travel",
    "reception",
    "concierge"
  ],
  "Human Resources": [
    "leadership",
    "outreach",
    "release",
    "coverage",
    "job-fairs",
    "staffing",
    "employers",
    "policies",
    "recruitment",
    "strategies",
    "payroll",
    "hiring",
    "jobseekers",
    "social",
    "engagement",
    "events",
    "interviews",
    "benefits",
    "culture",
    "vacancies",
    "reputation",
    "spokesperson",
    "placement",
    "branding",
    "press",
    "crisis",
    "relationships",
    "training",
    "salaries",
    "employee",
    "assessments",
    "candidates",
    "workforce",
    "performance",
    "retention",
    "job-descriptions",
    "audience",
    "recruiting",
    "diversity",
    "activations",
    "job-sites",
    "resumes",
    "productivity"
  ],
  "Individual & Family Services": [
    "reinsurers",
    "brokers",
    "mental illness",
    "mental health",
    "insurers",
    "rehabilitation",
    "parenting",
    "counseling",
    "grief support",
    "beneficiaries",
    "premiums",
    "after-school programs",
    "therapy",
    "actuaries",
    "domestic violence",
    "foster",
    "marriage counseling",
    "substance abuse",
    "deductibles",
    "claims",
    "underwriters",
    "child care",
    "adoption",
    "elderly care",
    "annuities",
    "homelessness"
  ],
  "Industrial Automation": [
    "automated processes",
    "internet of things (iot)",
    "ai",
    "embedded systems",
    "connected devices",
    "machine learning",
    "industrial control systems (ics)",
    "automation systems",
    "robotics",
    "industrial computing",
    "cybersecurity",
    "automation"
  ],
  "Information Technology And Services": [
    "mobile",
    "hardware",
    "cloud",
    "ai",
    "internet",
    "tech",
    "software",
    "automation",
    "iot",
    "robotics",
    "security",
    "artificial intelligence",
    "networking",
    "cybersecurity",
    "blockchain",
    "ecommerce",
    "programming"
  ],
  "International Affairs": [
    "development",
    "un",
    "terrorism",
    "transnational",
    "sanctions",
    "imports",
    "cross-border",
    "export",
    "treaty",
    "trade",
    "globalization",
    "immigration",
    "investment",
    "multilateralism",
    "conflict",
    "tariffs",
    "free-trade",
    "protectionism",
    "diplomacy",
    "foreign policy",
    "remittances",
    "international relations",
    "war",
    "aid",
    "human rights",
    "refugee"
  ],
  "Software & Internet": [
    "interface",
    "cellphone",
    "bandwidth",
    "technology",
    "mobile",
    "infrastructure",
    "coverage",
    "software",
    "carrier",
    "network",
    "hosting",
    "web-hosting",
    "apps",
    "ai",
    "platform",
    "wireless",
    "5g",
    "security",
    "spectrum",
    "lte",
    "payment-gateway",
    "device",
    "iot",
    "online-marketing",
    "search-engine",
    "telecom",
    "cloud",
    "internet",
    "social-media",
    "analytics",
    "roaming",
    "e-commerce",
    "web",
    "connectivity",
    "streaming",
    "program",
    "big-data",
    "video-conferencing",
    "networking"
  ],
  "Investment Banking": [
    "bond",
    "exchange",
    "derivative",
    "capital",
    "m&a",
    "mutual",
    "debt",
    "mergers",
    "ipo",
    "equity",
    "leverage",
    "wealth",
    "investment",
    "asset",
    "acquisitions",
    "fund",
    "liquidity",
    "trader",
    "financing",
    "hedge",
    "underwriting",
    "valuation",
    "performance",
    "investing",
    "syndication",
    "commodity",
    "structuring",
    "derivatives",
    "portfolio"
  ],
  "Legal Services": [
    "sessions",
    "courts",
    "perpetrator",
    "mergers",
    "taxation",
    "resolutions",
    "sentence",
    "lawyers",
    "security",
    "victim",
    "attorney",
    "acquisitions",
    "attorneys",
    "ombudsman",
    "trademarks",
    "parties",
    "arrest",
    "appeal",
    "injunction",
    "lawmakers",
    "bankruptcy",
    "governance",
    "contracts",
    "judges",
    "insurances",
    "due-diligence",
    "amendments",
    "crime",
    "justice",
    "safety",
    "vote",
    "evidence",
    "property",
    "corporate-governance",
    "mediation",
    "statutes",
    "trusts",
    "appeals",
    "bills",
    "prosecuting",
    "solicitors",
    "plea",
    "permits",
    "committees",
    "conciliation",
    "advocates",
    "court",
    "immigration",
    "adr",
    "tax",
    "debates",
    "agreements",
    "lawsuits",
    "constituents",
    "litigation",
    "regulations",
    "prosecution",
    "arbitration",
    "negotiation",
    "sentencing",
    "surveillance",
    "hearings",
    "precedent",
    "disputes",
    "jury",
    "veto",
    "insolvency",
    "investigation",
    "defense",
    "antitrust",
    "intellectual property",
    "compliance",
    "regulatory",
    "judge",
    "ipos",
    "lawyer",
    "police",
    "restructuring",
    "licensing",
    "legislation",
    "legislature",
    "law",
    "laws",
    "firearms",
    "verdict"
  ],
  "Travel, Recreation, And Leisure": [
    "resort",
    "cycling",
    "adventure",
    "tourism",
    "golf",
    "leisure",
    "shopping",
    "camping",
    "ski",
    "attractions",
    "flight",
    "vacations",
    "parks",
    "explorer",
    "sightseer",
    "vacation",
    "hiking",
    "sightseeing",
    "amusement",
    "resorts",
    "activity",
    "traveler",
    "festivals",
    "attraction",
    "concerts",
    "boating",
    "lodging",
    "hotel",
    "theme park",
    "cruise",
    "tourist",
    "aquatic",
    "adventure park",
    "restaurants",
    "travel",
    "dining"
  ],
  "Manufacturing": [
    "naval",
    "supply chain",
    "logistics",
    "workers",
    "freight",
    "tugboats",
    "wagon",
    "factory",
    "robotics",
    "locomotive",
    "automation",
    "shipbuilding",
    "berths",
    "wheels",
    "machines",
    "wharves",
    "manufacture",
    "anchors",
    "shipwrights",
    "harbors",
    "aerospace",
    "coupling",
    "propellers",
    "labor",
    "gauge",
    "production",
    "spare-parts",
    "rigging",
    "engineering",
    "track",
    "cranes",
    "keels",
    "dry-docks",
    "ships",
    "components",
    "navalcraft",
    "automobile",
    "railroad",
    "carriage",
    "coupler",
    "turbine",
    "boiler",
    "passenger",
    "design",
    "hulls",
    "axle",
    "assembly",
    "textile",
    "metals",
    "marinas"
  ],
  "Marketing And Advertising": [
    "research",
    "roi",
    "analysis",
    "trends",
    "strategies",
    "product",
    "advertise",
    "products",
    "forecasting",
    "consumer",
    "engagement",
    "campaign",
    "advisory",
    "reports",
    "promotion",
    "profiles",
    "analytics",
    "placement",
    "branding",
    "marketing",
    "ads",
    "strategy",
    "digital",
    "insight",
    "segmentation",
    "broadcast",
    "surveys"
  ],
  "Mechanical Or Industrial Engineering": [
    "turning",
    "robotics",
    "lathes",
    "fabrication",
    "cnc",
    "tooling",
    "automation",
    "welding",
    "machining",
    "machinery",
    "parts",
    "casting",
    "testing",
    "facility",
    "drilling",
    "forging",
    "hydraulics",
    "grinding",
    "sustainability",
    "extrusion",
    "milling",
    "pneumatics"
  ],
  "Military": [
    "combat",
    "navy",
    "radar",
    "defense",
    "squadron",
    "tank",
    "forces",
    "aircraft",
    "missile",
    "regiment",
    "battalion",
    "airforce",
    "military",
    "marine",
    "weapon",
    "armed"
  ],
  "Museums And Institutions": [
    "artifact",
    "heritage",
    "gallery",
    "antiquity",
    "archaeological",
    "historical",
    "archaeology",
    "exhibition",
    "antiquities",
    "sculpture",
    "museum",
    "institution",
    "art",
    "conservation",
    "preservation",
    "paintings",
    "archaeologist",
    "curator"
  ],
  "Nanotechnology": [
    "nanoelectromechanical",
    "nanomedicine",
    "nanoscience",
    "nanoelectronics",
    "nanoscale",
    "nanodevice",
    "nanomachine",
    "nanochip",
    "nanofabrication",
    "nanobiotechnology",
    "nanotechnology",
    "nanolithography",
    "nanomaterial",
    "nanoparticle",
    "quantum-dot"
  ],
  "Non-profit": [
    "accountability",
    "philanthropy",
    "nonprofit",
    "nonprofits",
    "volunteers",
    "donation",
    "community",
    "social impact",
    "cause",
    "volunteer",
    "charity",
    "governance",
    "endowments",
    "endowment",
    "donations",
    "sustainability",
    "impact",
    "grants",
    "donors",
    "grant",
    "transparency",
    "impact investing",
    "fundraising",
    "volunteering"
  ],
  "Outsourcing/offshoring": [
    "multi-sourcing",
    "labor-market",
    "global-workforce",
    "cost-cutting",
    "outsourcing",
    "nearshoring",
    "contracting",
    "remote",
    "talent-sourcing",
    "automation-strategies",
    "labor-costs",
    "offshoring",
    "globalization",
    "subcontracting",
    "labor",
    "outsourced"
  ],
  "Political Organization": [
    "activism",
    "vote",
    "leadership",
    "taxation",
    "initiative",
    "election",
    "policy",
    "political",
    "diplomacy",
    "budget",
    "government",
    "lobby",
    "interest",
    "advocacy",
    "campaign",
    "legislation",
    "economist"
  ],
  "Public Safety": [
    "rescue",
    "crime",
    "fire",
    "emergency",
    "police",
    "disaster",
    "security",
    "911",
    "accident",
    "safety"
  ],
  "Real Estate & Construction": [
    "foreclosure",
    "architecture",
    "kitchen",
    "supermarket",
    "leasing",
    "development",
    "rental",
    "hosts",
    "project",
    "refinance",
    "realty",
    "waitresses",
    "promotion",
    "grocery",
    "financing",
    "customers",
    "brand",
    "stock",
    "zoning",
    "supplies",
    "warehouse",
    "menu",
    "disposition",
    "survey",
    "renovation",
    "cuisine",
    "building",
    "fastfood",
    "aisle",
    "tenant",
    "landlord",
    "delivery",
    "eateries",
    "retail",
    "chef",
    "planning",
    "waiters",
    "shelves",
    "contractor",
    "appraisal",
    "property",
    "restaurants",
    "infrastructure",
    "plumber",
    "capital",
    "takeout",
    "property tax",
    "store",
    "baristas",
    "cashier",
    "developer",
    "franchises",
    "regulations",
    "electrician",
    "inventory",
    "dining",
    "residential",
    "surveyor",
    "permit",
    "shopping",
    "estimate",
    "construction",
    "lease",
    "commercial",
    "patrons",
    "mortgage"
  ],
  "Religious Institutions": [
    "church",
    "judaism",
    "missions",
    "devotion",
    "cathedral",
    "islam",
    "prayer",
    "clergy",
    "theology",
    "charities",
    "christianity",
    "faith",
    "scripture",
    "sacraments",
    "synagogue",
    "worship",
    "evangelism",
    "mosque"
  ],
  "Security And Investigations": [
    "monitoring",
    "access",
    "fraud",
    "cybercrime",
    "intelligence",
    "theft",
    "biometrics",
    "hacking",
    "investigation",
    "identity",
    "protection",
    "threats",
    "security",
    "surveillance",
    "risk",
    "compliance",
    "insider"
  ],
  "Sports": [
    "stadium",
    "archery",
    "tournament",
    "camping",
    "bicycles",
    "match",
    "squash",
    "field",
    "game",
    "gear",
    "hunting",
    "team",
    "coach",
    "sponsor",
    "skateboards",
    "athlete",
    "racquetball",
    "apparel",
    "footwear",
    "fishing",
    "sports",
    "fitness",
    "surfboards",
    "record",
    "boating",
    "equipment",
    "referee",
    "rule",
    "athletics",
    "outdoor",
    "league",
    "spectator"
  ],
  "Telecommunications": [
    "dsl",
    "fibre",
    "satellite",
    "mobile",
    "telecom",
    "wireless",
    "infrastructure",
    "cloud",
    "voip",
    "isp",
    "5g",
    "broadcast",
    "spectrum",
    "networking",
    "cell"
  ],
  "Textiles": [
    "yarns",
    "fabrics",
    "garments",
    "weaving",
    "apparel",
    "spinning",
    "knitting",
    "financing",
    "regulations",
    "exports",
    "safety",
    "textiles",
    "dyes",
    "designing"
  ],
  "Wholesale": [
    "logistics",
    "packaging",
    "procurement",
    "consumers",
    "manufacturing",
    "wholesalers",
    "pricing strategy",
    "transportation",
    "distribution",
    "demand",
    "store",
    "merchandise",
    "supply",
    "exporters",
    "trade",
    "manufacturers",
    "importers",
    "warehousing",
    "shipping",
    "delivery",
    "retail",
    "sourcing",
    "branding",
    "advertising",
    "market",
    "retailers",
    "sale",
    "commodities",
    "shopping centers",
    "suppliers",
    "inventory",
    "distributors"
  ],
  "Writing And Editing": [
    "print",
    "writing",
    "book",
    "grammar",
    "editing",
    "distribution",
    "content",
    "author",
    "publishing",
    "style",
    "advertising",
    "printing",
    "online",
    "journalism",
    "circulation",
    "digital",
    "design",
    "copywriting",
    "magazine",
    "newspaper",
    "proofreading",
    "subediting",
    "blogging",
    "subscription",
    "editor"
  ],
  "Business Services": [
    "Accounting",
    "Auditing",
    "Banking",
    "Consulting",
    "Investment",
    "Outsourcing",
    "Logistics",
    "Legal",
    "Insurance",
    "Taxation",
    "Technology",
    "Advertising",
    "Marketing",
    "Human Resources",
    "Facilities"
  ],
  "Civic & Social Organisation": [
    "Nonprofit",
    "Philanthropy",
    "Charities",
    "Community",
    "Volunteering",
    "Advocacy",
    "Fundraising",
    "Social",
    "Causes",
    "Projects",
    "Activism",
    "Donations"
  ],
  "Consumer Services": [
    "Retail",
    "Shopping",
    "Logistics",
    "Ecommerce",
    "Delivery",
    "Restaurant",
    "Grocery",
    "Apparel",
    "Manufacturing",
    "Tourism",
    "Airlines",
    "Hotels",
    "Car-rentals",
    "Vacations",
    "Leisure"
  ],
  "Events Services": [
    "Events",
    "Venues",
    "Catering",
    "Decorations",
    "Entertainment",
    "Planning",
    "Lighting",
    "Logistics",
    "Rentals",
    "Transportation"
  ],
  "Building Materials": [
    "Cement",
    "Sand",
    "Brick",
    "Mortar",
    "Concrete",
    "Aggregate",
    "Gypsum",
    "Plywood",
    "Timber",
    "Paints",
    "Coatings",
    "Roofing",
    "Insulation",
    "Plumbing",
    "Flooring",
    "Tiles"
  ],
  "Management Consulting": [
    "Consultants",
    "Strategy",
    "Advice",
    "Solutions",
    "Clients",
    "Projects",
    "Processes",
    "Outsourcing",
    "Mergers",
    "Acquisitions",
    "Restructuring",
    "Reorganization",
    "Costing",
    "Benchmarking",
    "Transformation",
    "Competitiveness"
  ],
  "Research": [
    "Biotech",
    "Pharmaceuticals",
    "Molecular",
    "Genetics",
    "Genomics",
    "Clinical",
    "Diagnostics",
    "Biomarkers",
    "Reagents",
    "Researching",
    "Laboratories",
    "Technologies",
    "Patents",
    "Publications",
    "Protocols",
    "Analyzing",
    "Statistics",
    "Vaccines",
    "Therapies"
  ],
  "Translation And Localisation": [
    "Translations",
    "Localisations",
    "Localization",
    "Globalization",
    "Multilingual",
    "Interpreting",
    "Terminology",
    "Localization Strategies",
    "Localization Processes",
    "Localization Tools",
    "Localization Challenges",
    "Localization Quality",
    "Localization Costs",
    "Localization Markets",
    "Localization Solutions"
  ]
}


# In[8]: Converting the Dataset to format on which SpaCy NER model trains

nlpe = spacy.load('en_core_web_sm')

# Add entity labels to the NER model
ner = nlpe.get_pipe("ner")
for entity, keywords_list in Indus.items():
    ner.add_label(entity)

# Initialize the training data
TRAIN_DATA = []

# Function to find entities in the text and label them
def label_entities(text, keywords):
    entities = []
    words = text.split()  # Split the text into words
    for entity, keywords_list in keywords.items():
        for keyword in keywords_list:
            for word in words:
                if word.lower() == keyword.lower():  # Check for a whole word match
                    start = text.find(word)
                    end = start + len(word)
                    entities.append((start, end, entity))
    return entities

# Generate training data for the first 1000 news headlines
for item in data_list[:10000]:
    if 'news' in item and 'head' in item['news']:
        text = item['news']['head']
        entities = label_entities(text, Indus)
        if entities:
            # Sort entities by start position to avoid overlap
            entities.sort(key=lambda x: x[0])
            # Only label the first entity found
            TRAIN_DATA.append((text, {'entities': entities[:1]}))

print(f"the length of TRAIN_DATA is {len(TRAIN_DATA)} ")


# Training the Model 

import spacy
import random
from tqdm import tqdm
from spacy.training.example import Example
import time
from multiprocessing import Pool
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings("ignore", message="[W030]")
import sys

# Split TRAIN_DATA into training and validation sets
train_data, validation_data = train_test_split(TRAIN_DATA, test_size=0.2, random_state=42)

# Add labels from your existing model
for _, annotations in train_data:
    for ent in annotations.get('entities'):
        nlp.get_pipe("ner").add_label(ent[2])

other_pipes = [pipe for pipe in nlp.pipe_names if pipe != 'ner']
with nlp.disable_pipes(*other_pipes):  # only train NER
    optimizer = nlp.begin_training()
    best_loss = float('inf')  # Initialize a variable to track the best loss
    best_model = None  # Initialize a variable to store the best model
    n_iter = 1000  # Set the number of training iterations
    start_time = time.time()  # Record the start time

    def train_text(text_annotation):
        text, annotations = text_annotation
        example = Example.from_dict(nlp.make_doc(text), annotations)
        losses = {}
        nlp.update([example], drop=0.5, losses=losses)
        return losses

    consecutive_no_improvement = 0  # Initialize a counter for consecutive epochs with no improvement
    early_stopping_patience = 10  # Define the patience (number of epochs with no improvement before stopping)

    training_logs = []  # Initialize a list to store training logs

    # Redirect stdout to a log file
    log_file = open("training_ind_model.txt", "w")
    sys.stdout = log_file

    with Pool() as pool:  # Use multiprocessing for faster training
        for itn in range(n_iter):
            random.shuffle(train_data)  # Shuffle the training data

            # Training
            loss_results = list(tqdm(pool.imap(train_text, train_data), total=len(train_data)))
            total_loss = sum(loss['ner'] for loss in loss_results)
            average_loss = total_loss / len(train_data)

            # Validation
            validation_loss_results = list(tqdm(pool.imap(train_text, validation_data), total=len(validation_data)))
            validation_total_loss = sum(loss['ner'] for loss in validation_loss_results)
            validation_average_loss = validation_total_loss / len(validation_data)

            end_time = time.time()  # Record the end time
            time_taken = end_time - start_time  # Calculate the time taken for this iteration

            if validation_average_loss < best_loss:
                best_loss = validation_average_loss
                best_model = nlp.to_bytes()  # Save the best model
                consecutive_no_improvement = 0  # Reset the counter
                log = f"Iteration {itn + 1}: Best training loss: {average_loss:.4f}, Validation loss: {validation_average_loss:.4f}, Time taken: {time_taken:.2f} seconds"
                training_logs.append(log)
                print(log)
            else:
                consecutive_no_improvement += 1

                if consecutive_no_improvement >= early_stopping_patience:
                    log = f"Early stopping at iteration {itn + 1}: Validation loss has not improved for {early_stopping_patience} consecutive epochs."
                    training_logs.append(log)
                    print(log)
                    break
                else:
                    log = f"Iteration {itn + 1}: Training loss: {average_loss:.4f}, Validation loss: {validation_average_loss:.4f}, Time taken: {time_taken:.2f} seconds"
                    training_logs.append(log)
                    print(log)

    # Save the training logs to a file
    with open("training_ind_model.txt", "w") as log_file:
        for log in training_logs:
            log_file.write(log + "\n")

    # Save the best model to disk
    nlp.to_disk("archive/updated_ind_py")

    # Close the log file and reset stdout
    log_file.close()
    sys.stdout = sys.__stdout__

print("Training completed with early stopping.")







